In [216]:
import pandas as pd
import numpy as np

Chapter 5 - Getting Started with Pandas

In [217]:
from pandas import DataFrame, Series

# 5.1 Introduction to pandas Data Structures

### Series

In [218]:
obj = pd.Series([4, 7, -5, 3])

In [219]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [220]:
obj.values

array([ 4,  7, -5,  3])

In [221]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [222]:
obj2 = pd.Series([4,7,-5,4], index = ['a','b','d','c'])

In [223]:
obj2

a    4
b    7
d   -5
c    4
dtype: int64

In [224]:
obj2.index

Index(['a', 'b', 'd', 'c'], dtype='object')

In [225]:
obj2['a']

4

In [226]:
obj2['c']

4

In [227]:
obj2[['b','a','c']]

b    7
a    4
c    4
dtype: int64

In [228]:
obj2[obj2>0]

a    4
b    7
c    4
dtype: int64

In [229]:
obj2*2

a     8
b    14
d   -10
c     8
dtype: int64

In [230]:
np.exp(obj2)

a      54.598150
b    1096.633158
d       0.006738
c      54.598150
dtype: float64

In [231]:
'g' in obj2

False

In [232]:
'a' in obj2

True

In [233]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000, 'Utah':5000}

In [234]:
obj3=pd.Series(sdata)

In [235]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [236]:
states=['California','Ohio','Oregon','Texas']

In [237]:
obj4=pd.Series(sdata, index=states)

In [238]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [239]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [240]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [241]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [242]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [243]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [244]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [245]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [246]:
obj4.name='population'

In [247]:
obj4.index.name='state'

In [248]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [249]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [250]:
obj.index=['Bob','Steve','Jeff','Ryan']

In [251]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [252]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'], 'year':[2000,2001,2002,2001,2002,2003], 'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [253]:
frame=pd.DataFrame(data)

In [254]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [255]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [256]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [257]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [258]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [259]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [260]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [261]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [262]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [263]:
frame2['debt']=16.5

In [264]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [265]:
frame2['debt']=np.arange(6.)

In [266]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [267]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [268]:
frame2['debt']=val

In [269]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [270]:
frame2['eastern'] = frame2.state=='Ohio'

In [271]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [272]:
del frame2['eastern']

In [273]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [274]:
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [275]:
frame3=pd.DataFrame(pop)

In [276]:
frame3


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [277]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [278]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [279]:
pdata={'Ohio':frame3['Ohio'][:-1], 'Nevada':frame3['Nevada'][:2]}

In [280]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [281]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [282]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [283]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [284]:
frame2.values


array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [285]:
obj= pd.Series(range(3), index = ['a','b','c'])

In [286]:
index = obj.index

In [287]:
index

Index(['a', 'b', 'c'], dtype='object')

In [288]:
index[1:]

Index(['b', 'c'], dtype='object')

In [289]:
index[1]='d'

TypeError: Index does not support mutable operations

In [290]:
labels = pd.Index(np.arange(3))

In [291]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [292]:
obj2 =pd.Series([1.5,-2.5,0],index=labels)

In [293]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [294]:
obj2.index is labels

True

In [295]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [296]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [298]:
'Ohio' in frame3.columns

True

In [299]:
2003 in frame3.index

False

In [300]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [301]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 Essential Functionality

### Reindexing

In [302]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index = ['d','b','a','c'])

In [303]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [304]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [305]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [306]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])

In [307]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [308]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [309]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [310]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [311]:
frame2 = frame.reindex(['a','b','c','d'])

In [312]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [313]:
states = ['Texas','Utah','California']

In [314]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [315]:
frame.dtypes

Ohio          int64
Texas         int64
California    int64
dtype: object

In [316]:
frame.loc[['a','b','c','d'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

## So moving on...

### Dropping Entries from an Axis

In [317]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])

In [318]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [319]:
new_obj = obj.drop('c')

In [320]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [321]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [322]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio','Colorado','Utah','New York'], columns=['one', 'two', 'three', 'four'])

In [323]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [324]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [326]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [327]:
data.drop(['two','four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [328]:
obj.drop('c', inplace = True)

In [329]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection and Filtering

In [330]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])

In [331]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [332]:
obj['b']

1.0

In [333]:
obj[1]

1.0

In [334]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [336]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [337]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [338]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [339]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [340]:
obj['b':'c'] = 5

In [341]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [343]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'], columns = ['one','two','three','four'])

In [345]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [346]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [349]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [350]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [351]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [352]:
data <5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [353]:
data[data<5] = 0

In [354]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

In [355]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [356]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [357]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [358]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [359]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [361]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [362]:
ser = pd.Series(np.arange(3.))

In [363]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [366]:
ser[-1]

KeyError: -1

In [367]:
ser2=pd.Series(np.arange(3.), index=['a','b','c'])

In [368]:
ser2[-1]

2.0

In [370]:
ser[:1]

0    0.0
dtype: float64

In [372]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [373]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [375]:
s1=pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [376]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [377]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [378]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [379]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [382]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio','Texas','Colorado'])

In [383]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index = ['Utah','Ohio','Texas','Oregon'])

In [384]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [385]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [386]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [387]:
df1 = pd.DataFrame({'A':[1,2]})

In [388]:
df2 = pd.DataFrame({'B':[3,4]})

In [389]:
df1

A
0  1
1  2

In [390]:
df2

B
0  3
1  4

In [391]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### Aithmetic methods with fill values

In [392]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))

In [393]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

In [394]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [395]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [396]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [397]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [398]:
1/df1


a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [399]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [400]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

In [401]:
arr=np.arange(12.).reshape((3,4))

In [402]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [403]:
arr[0]

array([0., 1., 2., 3.])

In [404]:
arr-arr[0] #broadcasting

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [405]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [406]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [407]:
series = frame.iloc[0]

In [408]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [409]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [410]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [411]:
series2 = pd.Series(range(3), index = ['b','e','f'])

In [412]:
series2

b    0
e    1
f    2
dtype: int64

In [413]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [414]:
series3 = frame['d']

In [415]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [416]:
series3=frame['d']

In [417]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [418]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [419]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [430]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [431]:
frame

b         d         e
Utah    1.335411  1.707379 -0.174933
Ohio    1.560473  1.513350 -0.685544
Texas   0.569534  0.224741  1.086425
Oregon -1.024699  0.700551  0.826058

In [432]:
np.abs(frame)

b         d         e
Utah    1.335411  1.707379  0.174933
Ohio    1.560473  1.513350  0.685544
Texas   0.569534  0.224741  1.086425
Oregon  1.024699  0.700551  0.826058

In [423]:
f=lambda x: x.max() - x.min()

In [425]:
frame.apply(f)

b    1.389600
d    2.050440
e    1.219915
dtype: float64

In [426]:
frame.apply(f, axis = 'columns')

Utah      0.348192
Ohio      1.187424
Texas     0.361882
Oregon    1.821172
dtype: float64

In [433]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [434]:
frame.apply(f)

b         d         e
min -1.024699  0.224741 -0.685544
max  1.560473  1.707379  1.086425

In [435]:
format = lambda x: '%.2f' %x

In [436]:
frame.applymap(format)

b     d      e
Utah     1.34  1.71  -0.17
Ohio     1.56  1.51  -0.69
Texas    0.57  0.22   1.09
Oregon  -1.02  0.70   0.83

In [437]:
frame['e'].map(format)

Utah      -0.17
Ohio      -0.69
Texas      1.09
Oregon     0.83
Name: e, dtype: object

### Sorting and Ranking

In [438]:
obj = pd.Series(range(4), index = ['d','a','b','c'])

In [439]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [440]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index = ['three','one'], columns = ['d','a','b','c'])

In [441]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [442]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [443]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [444]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [445]:
obj = pd.Series ([4,7,-3,2])

In [446]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [448]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [449]:
obj = pd.Series([4,np.nan, 7, np.nan, -3,-2])

In [450]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5   -2.0
dtype: float64

In [451]:
obj.sort_values()

4   -3.0
5   -2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [452]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [453]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [454]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [455]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [456]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [457]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [458]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [460]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [461]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [462]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [463]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [464]:
obj = pd.Series(range(5), index = ['a','a','b','b','c'])

In [465]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [466]:
obj.index.is_unique

False

In [467]:
obj['a']

a    0
a    1
dtype: int64

In [468]:
obj['c']

4

In [469]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])

In [470]:
df

0         1         2
a -0.765910 -0.982990 -0.801824
a -1.295736 -0.431474 -0.200479
b -1.133115 -1.737299 -0.639098
b  0.277291  0.477316 -0.484997

In [471]:
df.loc['b']

0         1         2
b -1.133115 -1.737299 -0.639098
b  0.277291  0.477316 -0.484997

## Summarizing and Computing Descriptive Statistics